---
# https://taskfile.dev
version: '3'

tasks:
  install:
    desc: "🔧 Install dependencies"
    cmds:
      - echo "🔧 Installing dependencies.."
      - uv sync --all-extras --dev

  lint:
    silent: true
    desc: "🧹 Run linters"
    cmds:
      - echo "🧹 Running linters.."
      - uv run ruff format .
      - uv run ruff check . --fix
      - uv run mypy --pretty .

  lint-check:
    silent: true
    desc: "🧹 Check whether the codebase is linted"
    cmds:
      - uv run ruff format --check .
      - uv run ruff check .
      - uv run mypy --pretty .

  init:
    silent: true
    desc: "🆕 Initialize a new Pulumi stack"
    cmds:
      - uv run pulumi stack init

  select:
    silent: true
    desc: "🚂 Select a Stack"
    cmds:
      - uv run pulumi stack select

  up:
    silent: true
    aliases: [deploy]
    desc: "🔨 Deploy the infrastructure"
    cmds:
      - echo "🔨 Deploying the infrastructure.."
      - uv run pulumi up

  info:
    silent: true
    desc: "ℹ️ Show Pulumi stack info"
    cmds:
      - uv run pulumi stack

  down:
    silent: true
    aliases: [destroy]
    desc: "💥 Destroy the deployed infrastructure"
    cmds:
      - echo "💥 Destroying the infrastructure.."
      - uv run pulumi down

  copyright:
    aliases: [license]
    desc: 📜 Apply license headers
    cmds:
      - echo "📜 Applying license headers"
      - docker run  --rm -v $PWD:/github/workspace ghcr.io/apache/skywalking-eyes/license-eye:eb0e0b091ea41213f712f622797e37526ca1e5d6
        -v info -c .licenserc.yaml header fix

  copyright-check:
    aliases: [license-check]
    desc: 📜 Checking for license headers
    cmds:
      - echo "📜 Checking license headers"
      - docker run  --rm -v $PWD:/github/workspace ghcr.io/apache/skywalking-eyes/license-eye:eb0e0b091ea41213f712f622797e37526ca1e5d6
        -v info -c .licenserc.yaml header check

  deploy-dev:
    silent: true
    aliases: [up-dev]
    desc: "🔨 Deploy the backend infrastructure"
    cmds:
      - echo "🔨 Deploying the backend infrastructure.."
      - |
        uv run pulumi up \
          --target 'urn:pulumi:*::talk-to-my-docs::custom:datarobot:CustomModelDeployment$datarobot:index/deployment:Deployment::Talk to My Docs Deployment [*]' \
          --target 'urn:pulumi:*::talk-to-my-docs::custom:datarobot:CustomModelDeployment::Talk to My Docs LLM deployment [*]' \
          --target 'urn:pulumi:*::talk-to-my-docs::datarobot:index/predictionEnvironment:PredictionEnvironment::Talk to My Docs Prediction Environment [*]' \
          --target 'urn:pulumi:*::talk-to-my-docs::datarobot:index/useCase:UseCase::Talk to My Docs [*]' \
          --target 'urn:pulumi:*::talk-to-my-docs::custom:datarobot:CustomModelDeployment$datarobot:index/registeredModel:RegisteredModel::Talk to My Docs Registered Model [*]' \
          --target 'urn:pulumi:*::talk-to-my-docs::datarobot:index/customModel:CustomModel::Talk to My Docs Playground Model [*]' \
          --target 'urn:pulumi:*::talk-to-my-docs::datarobot:index/llmBlueprint:LlmBlueprint::Talk to My Docs LLM Blueprint [*]' \
          --target 'urn:pulumi:*::talk-to-my-docs::datarobot:index/playground:Playground::Talk to My Docs Playground [*]' \
          --target 'urn:pulumi:*::talk-to-my-docs::datarobot:index/appOauth:AppOauth::Talk to My Docs Google Client Secret [*]' \
          --target 'urn:pulumi:*::talk-to-my-docs::datarobot:index/appOauth:AppOauth::Talk to My Docs Box Client Secret [*]'

